name: puresoc-reports

services:
  puresoc-report-renderer:
    image: puresoc-report-renderer:local
    pull_policy: build
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.report-renderer
