import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";

import { LEGAL_CAVEAT_MESSAGE_KEY, PURESOC_LEGAL_CAVEAT } from "@puresoc/shared";
import {
  buildInternalReadinessEvidencePackageExport,
  buildInternalReadinessCsvExport,
  buildInternalReadinessReport,
  buildRomaniaNotificationDraftExport,
  ReportExportError,
  stableCsvExport,
  stableJsonExport
} from "../index";

const sourceReference = {
  sourceRecordId: "eu-nis2-art-21",
  title: "NIS2 Article 21",
  jurisdiction: "EU",
  article: "21",
  sourceVersion: "2022/2555"
};

describe("reports exports stable JSON contracts", () => {
  it("builds caveated internal readiness reports from stored analysis records with source references", () => {
    const report = buildInternalReadinessReport({
      organizationId: "org_reports",
      assessmentId: "assessment_reports",
      jurisdiction: "EU",
      generatedAt: "2026-04-30T10:00:00.000Z",
      catalogVersion: "phase-h-seed",
      analysisRecordedAt: "2026-04-30T09:00:00.000Z",
      controlResults: [
        {
          organizationId: "org_reports",
          assessmentId: "assessment_reports",
          controlId: "nis2.access-control.mfa",
          controlCode: "A21-MFA",
          jurisdiction: "EU",
          status: "needs_evidence",
          confidence: "medium",
          summary: "MFA evidence is missing.",
          evidenceArtifactIds: [],
          providerSignalIds: ["finding_1"],
          sourceReferences: [sourceReference]
        }
      ],
      gaps: [
        {
          organizationId: "org_reports",
          assessmentId: "assessment_reports",
          controlId: "nis2.access-control.mfa",
          jurisdiction: "EU",
          severity: "medium",
          summary: "Upload MFA evidence.",
          missingEvidence: ["MFA coverage export"],
          recommendedActions: ["Upload or link evidence: MFA coverage export"],
          sourceReferences: [sourceReference]
        }
      ],
      recommendations: [
        {
          id: "rec_1",
          organizationId: "org_reports",
          controlId: "nis2.access-control.mfa",
          jurisdiction: "EU",
          title: "Upload MFA coverage evidence",
          severity: "medium",
          summary: "Evidence is required for internal readiness.",
          evidenceRequired: true,
          sourceReferences: [sourceReference]
        }
      ],
      evidence: []
    });

    expect(report.legalCaveat).toBe(PURESOC_LEGAL_CAVEAT);
    expect(report.legalCaveat).toContain("not a legal opinion");
    expect(report.legalCaveatMessageKey).toBe(LEGAL_CAVEAT_MESSAGE_KEY);
    expect(report.legalCaveatLocale).toBe("en");
    expect(report.legalCaveatFallbackUsed).toBe(false);
    expect(report.legalCaveatFallbackReason).toBeUndefined();
    expect(report.legalCaveatRequestedLocale).toBeUndefined();
    expect(report.legalCaveatReviewStatus).toBe("source_approved");
    expect(report.locale).toBe("en");
    expect(report.provenance.source).toBe("stored_analysis");
    expect(report.sourceReferences).toHaveLength(1);
    expect(report.gaps[0]?.sourceReferences[0]?.sourceRecordId).toBe("eu-nis2-art-21");

    const csvExport = buildInternalReadinessCsvExport(report);
    expect(csvExport).toMatchObject({
      schemaVersion: "puresoc.export.internal_readiness_csv.v1",
      exportFormat: "csv",
      rowCount: 6,
      tableNames: ["metadata", "control_results", "gaps", "recommendations", "source_references"]
    });
    expect(csvExport.csv).toContain("table,record_key,control_id,control_code,jurisdiction");
    expect(csvExport.csv).toContain("metadata,legal_caveat");
    expect(csvExport.csv).toContain("control_results,nis2.access-control.mfa");
    expect(csvExport.csv).toContain("gaps,nis2.access-control.mfa:1");
    expect(csvExport.csv).toContain("recommendations,nis2.access-control.mfa:1");
    expect(csvExport.csv).toContain('"This assessment is generated by PureSOC/SiSoN');
    expect(csvExport.csv).not.toContain("publicUrl");
  });

  it("builds deterministic binary evidence packages with manifest, report, csv, and local evidence files", () => {
    const evidenceBody = Buffer.from("quarterly MFA attestation", "utf8");
    const evidenceHash = createHash("sha256").update(evidenceBody).digest("hex");
    const report = buildInternalReadinessReport({
      organizationId: "org_reports",
      assessmentId: "assessment_reports",
      jurisdiction: "EU",
      generatedAt: "2026-04-30T10:00:00.000Z",
      catalogVersion: "phase-h-seed",
      analysisRecordedAt: "2026-04-30T09:00:00.000Z",
      controlResults: [
        {
          organizationId: "org_reports",
          assessmentId: "assessment_reports",
          controlId: "nis2.access-control.mfa",
          controlCode: "A21-MFA",
          jurisdiction: "EU",
          status: "compliant",
          confidence: "medium",
          summary: "MFA evidence is present.",
          evidenceArtifactIds: ["evidence_mfa"],
          providerSignalIds: [],
          sourceReferences: [sourceReference]
        }
      ],
      gaps: [],
      recommendations: [],
      evidence: [
        {
          id: "evidence_mfa",
          organizationId: "org_reports",
          title: "Quarterly MFA Attestation",
          sourceType: "manual_upload",
          controlId: "nis2.access-control.mfa",
          jurisdiction: "EU",
          contentHashSha256: evidenceHash,
          mimeType: "text/plain",
          scanStatus: "clean",
          createdAt: "2026-04-30T09:30:00.000Z",
          linkedSourceRecordId: "eu-nis2-art-21"
        }
      ]
    });

    const packageExport = buildInternalReadinessEvidencePackageExport({
      report,
      evidenceFiles: [
        {
          artifactId: "evidence_mfa",
          title: "Quarterly MFA Attestation",
          mimeType: "text/plain",
          body: evidenceBody,
          contentHashSha256: evidenceHash
        }
      ]
    });

    expect(packageExport).toMatchObject({
      schemaVersion: "puresoc.export.internal_readiness_evidence_package.v1",
      exportFormat: "binary_evidence_package",
      mimeType: "application/x-tar",
      fileName: "puresoc-internal-readiness-assessment_reports.tar",
      contentHashSha256: expect.stringMatching(/^[a-f0-9]{64}$/)
    });
    expect(packageExport.manifest).toMatchObject({
      schemaVersion: "puresoc.export.internal_readiness_evidence_package_manifest.v1",
      legalCaveat: PURESOC_LEGAL_CAVEAT,
      exportLimits: {
        maxEvidenceFiles: 250,
        maxEvidenceFileBytes: 10_485_760,
        maxBundleBytes: 52_428_800
      },
      files: expect.arrayContaining([
        expect.objectContaining({ path: "reports/internal-readiness.json", role: "report_json" }),
        expect.objectContaining({ path: "reports/internal-readiness.csv", role: "report_csv" }),
        expect.objectContaining({
          path: "evidence/evidence_mfa-quarterly-mfa-attestation.txt",
          role: "evidence_artifact",
          evidenceArtifactId: "evidence_mfa"
        })
      ])
    });
    expect(packageExport.manifestJson).toContain("not a legal opinion");
    expect(packageExport.manifestJson).not.toContain("storageUri");
    expect(packageExport.manifestJson).not.toContain("publicUrl");

    const entries = readTarEntries(packageExport.bundle);
    expect(entries.map((entry) => entry.path)).toEqual([
      "manifest.json",
      "evidence/evidence_mfa-quarterly-mfa-attestation.txt",
      "reports/internal-readiness.csv",
      "reports/internal-readiness.json"
    ]);
    expect(entries.find((entry) => entry.path === "manifest.json")?.body.toString("utf8")).toBe(
      packageExport.manifestJson
    );
    expect(entries.find((entry) => entry.path === "reports/internal-readiness.json")?.body.toString("utf8")).toContain(
      '"schemaVersion": "puresoc.report.internal_readiness.v1"'
    );
    expect(entries.find((entry) => entry.path === "reports/internal-readiness.csv")?.body.toString("utf8")).toContain(
      "metadata,legal_caveat"
    );
    expect(
      entries.find((entry) => entry.path === "evidence/evidence_mfa-quarterly-mfa-attestation.txt")?.body.toString(
        "utf8"
      )
    ).toBe("quarterly MFA attestation");
  });

  it("rejects oversized local evidence packages before returning bundle bytes", () => {
    const firstEvidenceBody = Buffer.from("first evidence", "utf8");
    const secondEvidenceBody = Buffer.from("second evidence", "utf8");
    const firstEvidenceHash = createHash("sha256").update(firstEvidenceBody).digest("hex");
    const secondEvidenceHash = createHash("sha256").update(secondEvidenceBody).digest("hex");
    const report = buildInternalReadinessReport({
      organizationId: "org_reports",
      assessmentId: "assessment_reports",
      jurisdiction: "EU",
      generatedAt: "2026-04-30T10:00:00.000Z",
      catalogVersion: "phase-h-seed",
      analysisRecordedAt: "2026-04-30T09:00:00.000Z",
      controlResults: [],
      gaps: [],
      recommendations: [],
      evidence: [
        {
          id: "evidence_first",
          organizationId: "org_reports",
          title: "First Evidence",
          sourceType: "manual_upload",
          contentHashSha256: firstEvidenceHash,
          mimeType: "text/plain",
          scanStatus: "clean",
          createdAt: "2026-04-30T09:30:00.000Z"
        },
        {
          id: "evidence_second",
          organizationId: "org_reports",
          title: "Second Evidence",
          sourceType: "manual_upload",
          contentHashSha256: secondEvidenceHash,
          mimeType: "text/plain",
          scanStatus: "clean",
          createdAt: "2026-04-30T09:31:00.000Z"
        }
      ]
    });

    expectReportExportError(
      () =>
        buildInternalReadinessEvidencePackageExport({
          report,
          evidenceFiles: [],
          limits: {
            maxEvidenceFiles: 1
          }
        }),
      "evidence_package_too_many_evidence_files"
    );

    expectReportExportError(
      () =>
        buildInternalReadinessEvidencePackageExport({
          report,
          evidenceFiles: [
            {
              artifactId: "evidence_first",
              title: "First Evidence",
              mimeType: "text/plain",
              body: firstEvidenceBody,
              contentHashSha256: firstEvidenceHash
            }
          ],
          limits: {
            maxEvidenceFiles: 2,
            maxEvidenceFileBytes: 4
          }
        }),
      "evidence_package_evidence_file_too_large"
    );

    expectReportExportError(
      () =>
        buildInternalReadinessEvidencePackageExport({
          report,
          evidenceFiles: [
            {
              artifactId: "evidence_first",
              title: "First Evidence",
              mimeType: "text/plain",
              body: firstEvidenceBody,
              contentHashSha256: firstEvidenceHash
            },
            {
              artifactId: "evidence_second",
              title: "Second Evidence",
              mimeType: "text/plain",
              body: secondEvidenceBody,
              contentHashSha256: secondEvidenceHash
            }
          ],
          limits: {
            maxEvidenceFiles: 2,
            maxEvidenceFileBytes: 1024,
            maxBundleBytes: 512
          }
        }),
      "evidence_package_bundle_too_large"
    );
  });

  it("builds Romania notification draft exports with source-mapped fields", () => {
    const exportData = buildRomaniaNotificationDraftExport({
      organizationId: "org_ro",
      assessmentId: "assessment_ro",
      status: "draft",
      generatedAt: "2026-04-30T10:00:00.000Z",
      locale: "ro-RO",
      payload: {
        entityName: "Example SRL",
        contactEmail: "security@example.test"
      },
      sourceMappedFields: [
        {
          fieldKey: "entityName",
          value: "Example SRL",
          sourceReferences: [
            {
              sourceRecordId: "ro-workbook-notification-form",
              jurisdiction: "RO",
              sourceLocation: "Notification form!B4",
              fieldKey: "entityName"
            }
          ]
        }
      ],
      classificationRunId: "classification_1"
    });

    expect(exportData.legalCaveat).toContain("not a legal opinion");
    expect(exportData.locale).toBe("ro");
    expect(exportData.legalCaveatFallbackReason).toBe("missing_translation");
    expect(exportData.legalCaveatLocale).toBe("en");
    expect(exportData.legalCaveatRequestedLocale).toBe("ro-RO");
    expect(exportData.legalCaveatReviewStatus).toBe("source_approved");
    expect(exportData.legalCaveatFallbackUsed).toBe(true);
    expect(exportData.sourceMappedFields[0]).toMatchObject({
      fieldKey: "entityName",
      value: "Example SRL"
    });
    expect(exportData.sourceReferences[0]).toMatchObject({
      sourceRecordId: "ro-workbook-notification-form",
      fieldKey: "entityName"
    });
  });

  it("keeps JSON export shape stable", () => {
    const json = stableJsonExport({
      z: 1,
      a: {
        b: true,
        a: "first"
      }
    });

    expect(json).toMatchInlineSnapshot(`
      "{
        "a": {
          "a": "first",
          "b": true
        },
        "z": 1
      }
      "
    `);
  });

  it("escapes CSV cells deterministically", () => {
    const csv = stableCsvExport(["name", "summary"], [
      {
        name: "quoted",
        summary: 'Needs "quoted", multiline\nvalue'
      }
    ]);

    expect(csv).toBe('name,summary\nquoted,"Needs ""quoted"", multiline\nvalue"\n');
  });
});

const expectReportExportError = (run: () => unknown, code: ReportExportError["code"]): void => {
  try {
    run();
  } catch (error) {
    expect(error).toBeInstanceOf(ReportExportError);
    expect((error as ReportExportError).code).toBe(code);
    expect((error as ReportExportError).statusCode).toBe(413);
    return;
  }

  throw new Error(`Expected report export error ${code}.`);
};

const readTarEntries = (bundle: Uint8Array): Array<{ path: string; body: Buffer }> => {
  const entries: Array<{ path: string; body: Buffer }> = [];
  const body = Buffer.from(bundle);
  let offset = 0;

  while (offset < body.byteLength) {
    const header = body.subarray(offset, offset + 512);
    if (header.every((byte) => byte === 0)) {
      break;
    }

    const path = header.subarray(0, 100).toString("utf8").replace(/\0+$/, "");
    const sizeText = header.subarray(124, 136).toString("ascii").replace(/\0+$/, "").trim();
    const size = Number.parseInt(sizeText || "0", 8);
    const contentStart = offset + 512;
    const contentEnd = contentStart + size;
    entries.push({
      path,
      body: body.subarray(contentStart, contentEnd)
    });
    offset = contentStart + Math.ceil(size / 512) * 512;
  }

  return entries;
};
