export const schemaGroups = {
  identityAndOrganization: [
    "users",
    "identity_accounts",
    "local_credentials",
    "sessions",
    "mfa_factors",
    "organizations",
    "organization_members",
    "roles",
    "role_bindings",
    "audit_logs"
  ],
  customerBusinessMetadata: [
    "customer_profiles",
    "business_profiles",
    "business_locations",
    "business_contacts",
    "business_services",
    "business_service_countries",
    "business_nace_codes",
    "business_size_assessments",
    "jurisdiction_assessments",
    "ro_nis2_onboarding_progress",
    "customer_documents"
  ],
  connectorConfigurationAndTelemetry: [
    "provider_connections",
    "provider_credentials",
    "provider_permission_bundles",
    "provider_capabilities",
    "provider_sync_runs",
    "provider_sync_modules",
    "provider_raw_resources",
    "provider_normalized_resources",
    "provider_findings",
    "provider_recommendations",
    "provider_action_templates",
    "provider_action_runs"
  ],
  regulatoryAndCountryPackData: [
    "regulatory_frameworks",
    "regulatory_framework_versions",
    "regulatory_sources",
    "regulatory_source_versions",
    "regulatory_source_snapshots",
    "regulatory_review_tasks",
    "jurisdictions",
    "country_packs",
    "country_pack_versions",
    "regulatory_questions",
    "regulatory_options",
    "regulatory_answers",
    "regulatory_source_maps"
  ],
  complianceAnalysis: [
    "control_catalog",
    "control_versions",
    "control_legal_references",
    "control_provider_mappings",
    "control_evidence_requirements",
    "compliance_assessments",
    "ro_nis2_classification_runs",
    "compliance_control_results",
    "compliance_gaps",
    "readiness_plans",
    "readiness_plan_items",
    "risk_acceptances",
    "checklist_templates",
    "checklist_template_items",
    "checklist_runs",
    "checklist_run_items"
  ],
  evidenceReportsDashboardsExports: [
    "evidence_artifacts",
    "evidence_links",
    "evidence_access_logs",
    "generated_reports",
    "report_exports",
    "dashboard_snapshots",
    "dashboard_widgets",
    "notification_drafts",
    "ro_nis2_notification_drafts"
  ],
  billing: ["billing_customers", "billing_subscriptions", "billing_entitlements", "billing_events"]
} as const;

export const tenantOwnedTables = [
  "organization_members",
  "role_bindings",
  "audit_logs",
  "customer_profiles",
  "business_profiles",
  "business_locations",
  "business_contacts",
  "business_services",
  "business_service_countries",
  "business_nace_codes",
  "business_size_assessments",
  "jurisdiction_assessments",
  "ro_nis2_onboarding_progress",
  "customer_documents",
  "provider_connections",
  "provider_credentials",
  "provider_permission_bundles",
  "provider_capabilities",
  "provider_sync_runs",
  "provider_sync_modules",
  "provider_raw_resources",
  "provider_normalized_resources",
  "provider_findings",
  "provider_recommendations",
  "provider_action_runs",
  "regulatory_answers",
  "compliance_assessments",
  "ro_nis2_classification_runs",
  "compliance_control_results",
  "compliance_gaps",
  "readiness_plans",
  "readiness_plan_items",
  "risk_acceptances",
  "checklist_runs",
  "checklist_run_items",
  "evidence_artifacts",
  "evidence_links",
  "evidence_access_logs",
  "generated_reports",
  "report_exports",
  "dashboard_snapshots",
  "dashboard_widgets",
  "notification_drafts",
  "ro_nis2_notification_drafts",
  "billing_customers",
  "billing_subscriptions",
  "billing_entitlements"
] as const;

export type SchemaGroupName = keyof typeof schemaGroups;
export type TenantOwnedTable = (typeof tenantOwnedTables)[number];
