FROM node:22-alpine
WORKDIR /workspace
ENV CI=true
RUN corepack enable && corepack prepare pnpm@10.33.2 --activate
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm prisma:generate
CMD ["pnpm", "start:connector-runner"]
