FROM mcr.microsoft.com/playwright:v1.56.1-noble
WORKDIR /workspace
ENV CI=true
RUN corepack enable && corepack prepare pnpm@10.33.2 --activate
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm prisma:generate
EXPOSE 3002
CMD ["pnpm", "start:report-renderer"]
