FROM public.ecr.aws/docker/library/node:22-alpine
WORKDIR /workspace
ENV CI=true
RUN corepack enable && corepack prepare pnpm@10.33.2 --activate
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm prisma:generate
EXPOSE 3001
CMD ["pnpm", "start:api"]
