export const PURESOC_LEGAL_CAVEAT =
  "This assessment is generated by PureSOC/SiSoN based on configured regulatory sources, customer-provided answers, and connected provider telemetry. It is an internal readiness and evidence-support tool, not a legal opinion, certification, or substitute for advice from the relevant national competent authority, legal counsel, auditor, or cybersecurity assessor.";

export const findingSeverities = ["informational", "low", "medium", "high", "critical"] as const;

export type FindingSeverity = (typeof findingSeverities)[number];

export const actionableSeverities = ["low", "medium", "high", "critical"] as const;

export type ActionableSeverity = (typeof actionableSeverities)[number];

export const isActionableSeverity = (severity: FindingSeverity | string): severity is ActionableSeverity =>
  (actionableSeverities as readonly string[]).includes(severity);

export const requiredServiceNames = [
  "puresoc-web",
  "puresoc-api",
  "puresoc-worker",
  "puresoc-scheduler",
  "puresoc-connector-runner",
  "puresoc-regulatory-importer",
  "puresoc-report-renderer",
  "puresoc-postgres",
  "puresoc-redis",
  "puresoc-object-storage"
] as const;

export type PureSocServiceName = (typeof requiredServiceNames)[number];
