export const PURESOC_LEGAL_CAVEAT =
  "This assessment is generated by PureSOC/SiSoN based on configured regulatory sources, customer-provided answers, and connected provider telemetry. It is an internal readiness and evidence-support tool, not a legal opinion, certification, or substitute for advice from the relevant national competent authority, legal counsel, auditor, or cybersecurity assessor.";

export const supportedLocales = ["en", "ro"] as const;

export type PureSocLocale = (typeof supportedLocales)[number];

export const defaultLocale: PureSocLocale = "en";

export const LEGAL_CAVEAT_MESSAGE_KEY = "puresoc.legal_caveat.internal_readiness.v1";

export const PURESOC_MESSAGE_KEYS = {
  apiSessionLabel: "puresoc.auth.api_session.label.v1",
  approvalQueueLabel: "puresoc.product.approval_queue.label.v1",
  dashboardLabel: "puresoc.product.dashboard.label.v1",
  emailLabel: "puresoc.auth.email.label.v1",
  evidenceReportsLabel: "puresoc.product.evidence_reports.label.v1",
  internalReadinessConsoleLabel: "puresoc.product.internal_readiness_console.label.v1",
  internalReadinessLabel: "puresoc.product.internal_readiness.label.v1",
  legalCaveat: LEGAL_CAVEAT_MESSAGE_KEY,
  passwordLabel: "puresoc.auth.password.label.v1",
  signInTitle: "puresoc.auth.sign_in.title.v1",
  sourceMappedLabel: "puresoc.status.source_mapped.label.v1",
  storedAggregateLabel: "puresoc.source.stored_aggregate.label.v1"
} as const;

export type PureSocGlobalMessageKey = (typeof PURESOC_MESSAGE_KEYS)[keyof typeof PURESOC_MESSAGE_KEYS];

export type PureSocMessageKind = "country_pack_notification" | "legal" | "product";

export type PureSocMessageReviewStatus = "demo_safe" | "requires_product_legal_approval" | "source_approved";

export type PureSocMessageFallbackReason = "missing_translation" | "unsupported_locale";

export interface LocaleResolution {
  fallbackReason?: PureSocMessageFallbackReason;
  fallbackUsed: boolean;
  locale: PureSocLocale;
  requestedLocale?: string;
}

export interface PureSocMessageCatalogEntry<TKey extends string = string> {
  defaultLocale?: PureSocLocale;
  messageKey: TKey;
  messageKind: PureSocMessageKind;
  reviewStatusByLocale?: Partial<Record<PureSocLocale, PureSocMessageReviewStatus>>;
  translations: Partial<Record<PureSocLocale, string>>;
}

export type PureSocMessageCatalog<TKey extends string = string> = Record<TKey, PureSocMessageCatalogEntry<TKey>>;

export interface LocalizedMessageResolution {
  fallbackReason?: PureSocMessageFallbackReason;
  fallbackUsed: boolean;
  messageKey: string;
  messageKind: PureSocMessageKind;
  normalizedLocale: PureSocLocale;
  requestedLocale?: string;
  reviewStatus: PureSocMessageReviewStatus;
  resolvedLocale: PureSocLocale;
  text: string;
}

export interface LegalCaveatMessageResolution extends LocalizedMessageResolution {
  messageKey: typeof LEGAL_CAVEAT_MESSAGE_KEY;
  messageKind: "legal";
}

export const isPureSocLocale = (value: string): value is PureSocLocale =>
  (supportedLocales as readonly string[]).includes(value);

export const resolvePureSocLocale = (locale?: string | null): LocaleResolution => {
  const requestedLocale = locale?.trim() || undefined;
  const normalized = requestedLocale?.toLowerCase().replace("_", "-").split("-")[0];

  if (normalized && isPureSocLocale(normalized)) {
    return {
      fallbackUsed: false,
      locale: normalized,
      requestedLocale
    };
  }

  return {
    fallbackReason: requestedLocale === undefined ? undefined : "unsupported_locale",
    fallbackUsed: requestedLocale !== undefined,
    locale: defaultLocale,
    requestedLocale
  };
};

export const definePureSocMessageCatalog = <TKey extends string>(
  entries: readonly PureSocMessageCatalogEntry<TKey>[]
): PureSocMessageCatalog<TKey> =>
  Object.fromEntries(entries.map((entry) => [entry.messageKey, entry])) as PureSocMessageCatalog<TKey>;

const demoSafeProductReviewStatus: Partial<Record<PureSocLocale, PureSocMessageReviewStatus>> = {
  en: "source_approved",
  ro: "demo_safe"
};

export const pureSocMessageCatalog = definePureSocMessageCatalog<PureSocGlobalMessageKey>([
  {
    messageKey: LEGAL_CAVEAT_MESSAGE_KEY,
    messageKind: "legal",
    reviewStatusByLocale: {
      en: "source_approved"
    },
    translations: {
      en: PURESOC_LEGAL_CAVEAT
    }
  },
  {
    messageKey: PURESOC_MESSAGE_KEYS.internalReadinessLabel,
    messageKind: "product",
    reviewStatusByLocale: demoSafeProductReviewStatus,
    translations: {
      en: "Internal readiness",
      ro: "Pregatire interna"
    }
  },
  {
    messageKey: PURESOC_MESSAGE_KEYS.internalReadinessConsoleLabel,
    messageKind: "product",
    reviewStatusByLocale: demoSafeProductReviewStatus,
    translations: {
      en: "PureSOC internal readiness console",
      ro: "Consola PureSOC pentru pregatire interna"
    }
  },
  {
    messageKey: PURESOC_MESSAGE_KEYS.dashboardLabel,
    messageKind: "product",
    reviewStatusByLocale: demoSafeProductReviewStatus,
    translations: {
      en: "Dashboard",
      ro: "Tablou de bord"
    }
  },
  {
    messageKey: PURESOC_MESSAGE_KEYS.evidenceReportsLabel,
    messageKind: "product",
    reviewStatusByLocale: demoSafeProductReviewStatus,
    translations: {
      en: "Evidence And Reports",
      ro: "Dovezi si rapoarte"
    }
  },
  {
    messageKey: PURESOC_MESSAGE_KEYS.approvalQueueLabel,
    messageKind: "product",
    reviewStatusByLocale: demoSafeProductReviewStatus,
    translations: {
      en: "Approval Queue",
      ro: "Coada de aprobari"
    }
  },
  {
    messageKey: PURESOC_MESSAGE_KEYS.apiSessionLabel,
    messageKind: "product",
    reviewStatusByLocale: demoSafeProductReviewStatus,
    translations: {
      en: "API session",
      ro: "Sesiune API"
    }
  },
  {
    messageKey: PURESOC_MESSAGE_KEYS.signInTitle,
    messageKind: "product",
    reviewStatusByLocale: demoSafeProductReviewStatus,
    translations: {
      en: "Sign in",
      ro: "Autentificare"
    }
  },
  {
    messageKey: PURESOC_MESSAGE_KEYS.emailLabel,
    messageKind: "product",
    reviewStatusByLocale: demoSafeProductReviewStatus,
    translations: {
      en: "Email",
      ro: "Email"
    }
  },
  {
    messageKey: PURESOC_MESSAGE_KEYS.passwordLabel,
    messageKind: "product",
    reviewStatusByLocale: demoSafeProductReviewStatus,
    translations: {
      en: "Password",
      ro: "Parola"
    }
  },
  {
    messageKey: PURESOC_MESSAGE_KEYS.sourceMappedLabel,
    messageKind: "product",
    reviewStatusByLocale: demoSafeProductReviewStatus,
    translations: {
      en: "Source mapped",
      ro: "Mapat la sursa"
    }
  },
  {
    messageKey: PURESOC_MESSAGE_KEYS.storedAggregateLabel,
    messageKind: "product",
    reviewStatusByLocale: demoSafeProductReviewStatus,
    translations: {
      en: "Stored aggregate",
      ro: "Agregat stocat"
    }
  }
]);

export const resolvePureSocMessage = (input: {
  catalog?: PureSocMessageCatalog;
  locale?: string | null;
  messageKey: string;
}): LocalizedMessageResolution => {
  const catalog: Record<string, PureSocMessageCatalogEntry> = input.catalog ?? pureSocMessageCatalog;
  const entry = catalog[input.messageKey];
  if (!entry) {
    throw new Error(`Unknown PureSOC message key: ${input.messageKey}`);
  }

  const localeResolution = resolvePureSocLocale(input.locale);
  const defaultMessageLocale = entry.defaultLocale ?? defaultLocale;
  const localizedText = entry.translations[localeResolution.locale];
  const resolvedLocale = localizedText ? localeResolution.locale : defaultMessageLocale;
  const fallbackReason = localeResolution.fallbackReason ?? (localizedText ? undefined : "missing_translation");
  const fallbackText = entry.translations[defaultMessageLocale];

  if (!localizedText && !fallbackText) {
    throw new Error(`PureSOC message key has no ${defaultMessageLocale} fallback: ${input.messageKey}`);
  }

  return {
    fallbackReason,
    fallbackUsed: Boolean(fallbackReason),
    messageKey: entry.messageKey,
    messageKind: entry.messageKind,
    normalizedLocale: localeResolution.locale,
    requestedLocale: localeResolution.requestedLocale,
    reviewStatus: entry.reviewStatusByLocale?.[resolvedLocale] ?? "demo_safe",
    resolvedLocale,
    text: localizedText ?? fallbackText ?? ""
  };
};

export const resolveLegalCaveatMessage = (locale?: string | null): LegalCaveatMessageResolution =>
  resolvePureSocMessage({
    locale,
    messageKey: LEGAL_CAVEAT_MESSAGE_KEY
  }) as LegalCaveatMessageResolution;

export const findingSeverities = ["informational", "low", "medium", "high", "critical"] as const;

export type FindingSeverity = (typeof findingSeverities)[number];

export const actionableSeverities = ["low", "medium", "high", "critical"] as const;

export type ActionableSeverity = (typeof actionableSeverities)[number];

export const isActionableSeverity = (severity: FindingSeverity | string): severity is ActionableSeverity =>
  (actionableSeverities as readonly string[]).includes(severity);

export type Confidence = "low" | "medium" | "high";

export interface SourceReference {
  sourceRecordId: string;
  article?: string;
  paragraph?: string;
  annex?: string;
  nationalReference?: string;
  sourceUrl?: string;
  sourceVersion?: string;
  label?: string;
}

export type ProviderFindingForComplianceStatus = "open" | "acknowledged" | "resolved" | "suppressed";

export interface ProviderFindingForCompliance {
  id: string;
  providerKey: string;
  moduleKey: string;
  findingKey: string;
  title: string;
  summary: string;
  severity: FindingSeverity;
  status: ProviderFindingForComplianceStatus;
  evidence: Record<string, unknown>;
}

export type RecommendationActionType =
  | "manual"
  | "guided"
  | "technical"
  | "process"
  | "evidence_upload"
  | "country_registration"
  | "incident_reporting";

export type RecommendationAutomationMode = "manual" | "guided" | "preflightable" | "executable_later";

export type RecommendationStatus = "proposed" | "accepted" | "planned" | "completed" | "dismissed";

export interface RecommendationSummary {
  id: string;
  organizationId?: string;
  sourceFindingId?: string;
  sourceFindingIds?: readonly string[];
  manualTaskIds?: readonly string[];
  controlId: string;
  jurisdiction: string;
  title: string;
  summary: string;
  severity?: ActionableSeverity;
  confidence?: Confidence;
  recommendationType: RecommendationActionType;
  automationMode: RecommendationAutomationMode;
  requiredPermissions: readonly string[];
  requiredLicense: readonly string[];
  expectedChange?: string;
  blastRadius?: string;
  manualFallback?: string;
  evidenceRequired: boolean;
  status: RecommendationStatus;
  sourceReferences?: readonly SourceReference[];
}

export const requiredServiceNames = [
  "puresoc-web",
  "puresoc-api",
  "puresoc-worker",
  "puresoc-scheduler",
  "puresoc-connector-runner",
  "puresoc-regulatory-importer",
  "puresoc-report-renderer",
  "puresoc-postgres",
  "puresoc-redis",
  "puresoc-object-storage"
] as const;

export type PureSocServiceName = (typeof requiredServiceNames)[number];
