export const PURESOC_LEGAL_CAVEAT =
  "This assessment is generated by PureSOC/SiSoN based on configured regulatory sources, customer-provided answers, and connected provider telemetry. It is an internal readiness and evidence-support tool, not a legal opinion, certification, or substitute for advice from the relevant national competent authority, legal counsel, auditor, or cybersecurity assessor.";

export const findingSeverities = ["informational", "low", "medium", "high", "critical"] as const;

export type FindingSeverity = (typeof findingSeverities)[number];

export const actionableSeverities = ["low", "medium", "high", "critical"] as const;

export type ActionableSeverity = (typeof actionableSeverities)[number];

export const isActionableSeverity = (severity: FindingSeverity | string): severity is ActionableSeverity =>
  (actionableSeverities as readonly string[]).includes(severity);

export type Confidence = "low" | "medium" | "high";

export interface SourceReference {
  sourceRecordId: string;
  article?: string;
  paragraph?: string;
  annex?: string;
  nationalReference?: string;
  sourceUrl?: string;
  sourceVersion?: string;
  label?: string;
}

export type ProviderFindingForComplianceStatus = "open" | "acknowledged" | "resolved" | "suppressed";

export interface ProviderFindingForCompliance {
  id: string;
  providerKey: string;
  moduleKey: string;
  findingKey: string;
  title: string;
  summary: string;
  severity: FindingSeverity;
  status: ProviderFindingForComplianceStatus;
  evidence: Record<string, unknown>;
}

export type RecommendationActionType =
  | "manual"
  | "guided"
  | "technical"
  | "process"
  | "evidence_upload"
  | "country_registration"
  | "incident_reporting";

export type RecommendationAutomationMode = "manual" | "guided" | "preflightable" | "executable_later";

export type RecommendationStatus = "proposed" | "accepted" | "planned" | "completed" | "dismissed";

export interface RecommendationSummary {
  id: string;
  organizationId?: string;
  sourceFindingId?: string;
  sourceFindingIds?: readonly string[];
  manualTaskIds?: readonly string[];
  controlId: string;
  jurisdiction: string;
  title: string;
  summary: string;
  severity?: ActionableSeverity;
  confidence?: Confidence;
  recommendationType: RecommendationActionType;
  automationMode: RecommendationAutomationMode;
  requiredPermissions: readonly string[];
  requiredLicense: readonly string[];
  expectedChange?: string;
  blastRadius?: string;
  manualFallback?: string;
  evidenceRequired: boolean;
  status: RecommendationStatus;
  sourceReferences?: readonly SourceReference[];
}

export const requiredServiceNames = [
  "puresoc-web",
  "puresoc-api",
  "puresoc-worker",
  "puresoc-scheduler",
  "puresoc-connector-runner",
  "puresoc-regulatory-importer",
  "puresoc-report-renderer",
  "puresoc-postgres",
  "puresoc-redis",
  "puresoc-object-storage"
] as const;

export type PureSocServiceName = (typeof requiredServiceNames)[number];
